### ISSUE TITLE
Incorrect sort order of transparent materials (Godot 4.x engine bug)

### ISSUE THREAD

**Issue by GeorgeS2019** [V-Sekai/godot-vrm#10]
deleted

**Comment by lyuma** [comment]
If a model doss not match the appearance of VRoidHub out of the box, that is a bug.
Could you please link me to the model you are testing with, or DM me the model if it is private? that would help me resolve the issue
Thanks for the report.

regarding name of sub-surfaces, can you tell me what the names are supposed to be on the original model? how do they appear in other tools such as Unity. I will implement it if you can show me where this data comes from.

**Comment by GeorgeS2019** [comment]
@lyuma 
- [Zero model](https://hub.vroid.com/en/characters/1875782176036343316/models/5601221667736184962)
- I have not used UniVRM yet, only godot
- The naming issue could be (perhaps deeper) inherent with the GLTF implementation of Godot.  I will create additional issue to track this.

**Comment by lyuma** [comment]
unfortunately that model no longer allows download.
can you tell me the name of the shader for the broken eyebrow materials?

**Comment by GeorgeS2019** [comment]
@lyuma Appology here is the right [Zero](https://hub.vroid.com/en/characters/1598457303824764453/models/4629773375945291691).  => please download. I am new to this. did not realize there are more than one Zero

**Comment by fire** [comment]
[825401423553194976.zip](https://github.com/V-Sekai/godot-vrm/files/6446196/825401423553194976.zip)


![image](https://user-images.githubusercontent.com/32321/117546913-a70bc180-afe1-11eb-953b-a65533010ab6.png)

https://hub.vroid.com/en/characters/1598457303824764453/models/4629773375945291691

**Comment by lyuma** [comment]
Hi @GeorgeS2019 I was unable to reproduce your issue

![image](https://user-images.githubusercontent.com/39946030/117547105-b0495e00-afe2-11eb-8082-4c85e3677f14.png)

I really, *really* appreciate your help testing godot-vrm.

Sorry if it came off harsh. You are literally the first user to test out the new version of godot-vrm and I'm really pleased you got a chance to use it

**Comment by GeorgeS2019** [comment]
@lyuma it is a pleasure to see your passion making godot-vrm works.  You are responding positive to feedback. I totally understand and share that others to try and learn the culture reflected by VRM.

**Comment by lyuma** [comment]
So to get back to the OP issue... I think you may have just hit an engine bug in Godot 4.x - since I am not able to reproduce the issue with that model.

(It is dangerous to test in this pre-alpha, unstable engine version. Bugs are rampant)

The bug I think you ran into is one where the faces randomly get flipped inside out. One trigger for this type of issue is opening the same model in two scene tabs. We just need to wait for Godot to fix the issues in Godot 4.x, but Godot is still working on features and so they probably are not going to start bug hunting for a few months.

That said, I'll keep this issue in mind and I'll be on the lookout for it. If you want stability, you'll need to use Godot 3.x - I'm close to finishing my backports to that version.

**Comment by GeorgeS2019** [comment]
@lyuma  backport to Godot 3.x would be an excellent idea. Thanks for keeping up the goal.

**Comment by lyuma** [comment]
Ok another theory. This model has multiple transparent materials and it's using Render Priority on some of them. Render Priority is broken on Godot master. So it could be that on your build of Godot, the transparent materials render in a different order than on mine. (it might be undefined)

**Comment by GeorgeS2019** [comment]
@lyuma I had similar problems with non VRM models. Often I do not have enough experience to know why. Thanks for your suggestion. Something to think about :-)

**Comment by GeorgeS2019** [comment]
@lyuma I should have closed this long time ago. Thx for reminder. :-)
