### ISSUE TITLE
Naming VRM Blendshapes

### ISSUE THREAD

**Issue by GeorgeS2019** [V-Sekai/godot-vrm#11]
Currently the imported Godot VRM shows only generic naming for blendshapes.

Morph 0 to Morph 53
<img src="https://user-images.githubusercontent.com/49812372/117542590-84959a80-b019-11eb-9ba9-fcb588e3954f.png" alt="drawing" width="250"/>

The expected display in e.g. UniVRM as [documented ](https://vrm.dev/en/docs/univrm/blendshape/univrm_blendshape/)here
<img src="https://user-images.githubusercontent.com/49812372/117542651-c6bedc00-b019-11eb-8550-9169a4f32042.png" alt="drawing" width="350"/>

I suspect the lack of comparable proper naming issue  (with respect to e.g. UniVRM) could be related to Godot GLTF implementation. Perhaps someone is able to suggest which issues are that and if that have been merged in Godot4 or back port to Godot 3.3

**Comment by fire** [comment]
Can use the merged feature in Godot Engine.

https://github.com/godotengine/godot/pull/42827

**Comment by GeorgeS2019** [comment]
@fire I am using the latest (TODAY) godot 4, it seems the naming of blendshapes (as claimed MERGED) is still not resolved.

**Comment by fire** [comment]
The feature from Godot Engine is allowing the renaming of bones, the vrm gdscript code still needs to parse the gltf2 vrm data and rename them.
