### ISSUE TITLE
[4.x only] outline turns black if OutlineMix = 0

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/godot-vrm#12]
![image](https://user-images.githubusercontent.com/39946030/118413266-3e60bc80-b653-11eb-9f8f-63ef9687459b.png)

**Comment by fire** [comment]
Need to recheck this.

**Comment by lyuma** [comment]
There were some bugs with how colors were mixed. If I recall, one such bug was a division by zero with the albedo color (due to how light multiplication is done in 4.x).

This bug is over a year old, and I do not think this is still a problem.

Since apparently the reproduction screenshot was of alicia's sleeve, I will upload a new armpit screenshot for comparison purposes showing that the outline is not black.
![image](https://github.com/V-Sekai/godot-vrm/assets/39946030/f2346e79-0544-4d47-9470-46d8e4cb6874)
