### ISSUE TITLE
Submit Godot-VRM to the godot AssetLib

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/godot-vrm#14]
We believe Godot-VRM is at a quality level to merit inclusion in Godot's Asset Library.

I will be submitting it with one of these icons:

![godot_vrm_logo](https://user-images.githubusercontent.com/39946030/120100285-d8654200-c0f4-11eb-8c79-9b70791bbf18.png)

![godot_vrm_icon](https://user-images.githubusercontent.com/39946030/120100280-d307f780-c0f4-11eb-8e3e-820a5a338974.png)

Here is a screenshot of MToon Shader Settings:
![MToon Shader Settings](https://user-images.githubusercontent.com/39946030/120100662-b5d42880-c0f6-11eb-885b-a8eef9f9110e.png)

**Comment by lyuma** [comment]
Submitted the asset.

**Asset Name**
VRM Importer and MToon Shader
**Description**
"VRM" is a file format for handling 3D humanoid avatar (3D model) data for VR applications. It is based on glTF2.0. ( https://vrm.dev )

This asset provides an importer for VRM characters, as well as a full implementation of the MToon Shader for Godot Engine.
**Category**
3D Tools
**License**
MIT
The license under which the asset is available. Check opensource.org for a more detailed description of each. In case an OSI-approved license you are using is missing, you might open an issue about it.
Note: The license you specify here should also be included in the repository you are submitting under a standard name, such as LICENSE or LICENSE.md
**Repository host**
GitHub
The site or service hosting your repository. If your repository host is missing, you might like to open an issue about it.
**Repository URL**
https://github.com/V-Sekai/godot-vrm
The URL you use to browse your repository.
Note: Do not give the clone URL (the one that ends in .git), but give the one you use to browse your code.
**Issues URL**
https://host.example/user/repository/issues
Optional, in case you are not using the one supplied by the repository host.
**Godot version**
3.2
**Asset Version**
1.1.0
**Download Commit**
04a77603dd3a480ec747036ac3d88d27d5856b44
The commit hash that should be downloaded. Expects 40 or 64 hexadecimal digits fully specifying a git commit.
**Icon URL**
https://user-images.githubusercontent.com/39946030/120100280-d307f780-c0f4-11eb-8e3e-820a5a338974.png
Add preview  Enable
**Type**
Image
**Image/YouTube Link**
https://raw.githubusercontent.com/V-Sekai/godot-vrm/04a77603dd3a480ec747036ac3d88d27d5856b44/vrm_samples/screenshot/vrm_sample_screenshot.png
**Link to thumbnail**
![thumbnail_1](https://user-images.githubusercontent.com/39946030/120101068-12384780-c0f9-11eb-87fc-f18cb25253b5.png)
Image Link
Add preview  Enable
**Type**
Video
**Image/YouTube Link**
https://www.youtube.com/watch?v=M7psmdcDHAo
**Link to thumbnail**
https://img.youtube.com/vi/M7psmdcDHAo/hqdefault.jpg
Add preview  Enable
**Type**
Image
**Image/YouTube Link**
https://user-images.githubusercontent.com/39946030/120100662-b5d42880-c0f6-11eb-885b-a8eef9f9110e.png
**Link to thumbnail**
![thumbnail_4](https://user-images.githubusercontent.com/39946030/120101069-12d0de00-c0f9-11eb-9515-35ac94dcb8b5.png)
Image Link

**Comment by fire** [comment]
https://godotengine.org/asset-library/asset/964

Released for 3.2. (not 3.3 latest).

**Comment by lyuma** [comment]
Adding another screenshot:
![image](https://user-images.githubusercontent.com/39946030/120117103-74686b00-c140-11eb-963b-c976805faeb9.png)

New text:
"VRM" is a file format for handling 3D humanoid avatar (3D model) data for VR applications. It is based on glTF2.0. ( https://vrm.dev/en )

This asset provides an importer for VRM characters, as well as a full implementation of the MToon Shader for Godot Engine. Enable the addons in "Project Settings..." → "Plugins"

「VRM」はVRアプリケーション向けの人型3Dアバター（3Dモデル）データを扱うためのファイルフォーマットです。glTF2.0をベースとしており、誰でも自由に利用することができます。 ( https://vrm.dev )

このアセットは、VRMの3Dアバターのインポーターを提供します。また、VRM Addon とは別に Godot 用の MToon シェーダーも同梱されています。「プロジェクト設定...」→「プラグイン」で有効にする。

New version:
1.1.1

New link:
eb5938a535caf400f586bf2945610987a5a84a6d
