### ISSUE TITLE
Next step for Godot VRM

### ISSUE THREAD

**Issue by GeorgeS2019** [V-Sekai/godot-vrm#29]
Sorry, I just found this. So I close the issue
https://github.com/V-Sekai/blog/blob/main/a-statement-on-the-walled-metaverse-ja.md

**Comment by lyuma** [comment]
To elaborate, godot-vrm is but one piece of the software stack for virtual worlds, social VR, or "metaverse" tech.

By being an open standard, VRM puts different platforms on equal footing, and has the positive side-effect of making it easy for people to buy or make models that you can be sure will work everywhere.

As for text-to-speech, there are open source projects delivering that. and in fact, I have met people in VR who use speech-to-text-to-speech to make a synthesized AI who speaks for you.

Probably of all the issues you brought up, the one that is within the purview and future vision of godot-vrm, is to enable VRM characters to play animations from compatible armatures: essentially animation retargeting onto a VRM rig, very similar to the sort of tech you see in other game engines. I hope to work on this someday and provide a complete animation system built on top of godot-vrm.

And https://vrm.dev/en is probably the best place to read more about the vision of the VRM format itself.

**Comment by GeorgeS2019** [comment]
@lyuma  I have signed up the discord. I need a Godot Avatar with capable of programming expression and sympathy, beyond skeletal animation. Great Job!

**Comment by GeorgeS2019** [comment]
@lyuma I am also interested of the latest AI behind the synthesized AI (content beyond the right voice and synthesized voice)
