### ISSUE TITLE
problems with 3.4 stable

### ISSUE THREAD

**Issue by Moecon** [V-Sekai/godot-vrm#30]
![imagen](https://user-images.githubusercontent.com/66885278/147891323-db58a335-defc-413d-9f23-137c49f8a2b9.png)
with this can install addon, but this error i don't correct
![imagen](https://user-images.githubusercontent.com/66885278/147891377-ce7bdcf4-7069-4f46-9487-ffdbbb53c9ef.png)
and i can't import model VRM
please help

**Comment by SaracenOne** [comment]
We should have an update to 3.4 compatibility branch now if you want to try it. We'll also try see if we can get the assetlib updated today
https://github.com/V-Sekai/godot-vrm/pull/28

**Comment by lyuma** [comment]
PR #28 was merged.  Release to AssetLib is pending.

**Comment by Moecon** [comment]
thank you soo much, for now work and i will save time
![imagen](https://user-images.githubusercontent.com/66885278/149345633-27b47a37-ed15-4c6b-b050-7aef9aae4c10.png)
this will take 4 hour of import
![imagen](https://user-images.githubusercontent.com/66885278/149346199-82b6a034-f891-41d8-8a8f-33c52e74fe20.png)
