### ISSUE TITLE
Port to vrm 1.0

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#40]
VRM 1.0 is upcoming.

**Comment by fire** [comment]
VRM 1 has released.

**Comment by fire** [comment]
Work has started. Will make issues as they appear.

**Comment by lyuma** [comment]
(Reopening because I think this was closed by mistake.)

Work is ongoing. See the https://github.com/V-Sekai/godot-vrm/tree/vrm1-wip branch.

**Comment by fire** [comment]
VRM1 has been merged into master. Report bugs as separate issues.
