### ISSUE TITLE
mtoon-shader EditorInspector is not suitable for godot4.0 alpha14 

### ISSUE THREAD

**Issue by FZelin** [V-Sekai/godot-vrm#44]
mtoon-shader EditorInspector is ot suitable for godot4.0 alpha14 

shader param is default ,not mtoon custom.

**Comment by fire** [comment]
Thanks, will look into this around next week.

**Comment by fire** [comment]
I mentioned this to @lyuma again.

**Comment by fire** [comment]
> can't inspect mtoon
> and godot crashes 
> https://github.com/V-Sekai/godot-vrm/issues/44

> Lyuma found the source of the bug.
> It seems to be an asymmetry in reference counting of the Object* used in EditorProperty in get_edited_object() when the object is in fact a RefCounted

**Comment by fire** [comment]
Need to recheck. It's been a while since Godot Engine 4.0 was in alpha.

**Comment by lyuma** [comment]
The engine bug got fixed. the code might still have a workaround in it but it's not needed.
