### ISSUE TITLE
How to import in runtime on Godot 4?

### ISSUE THREAD

**Issue by EibrielInv** [V-Sekai/godot-vrm#53]
According to the sample I need to import `vrm_loader.gd` but that file don't exists. And I can't find out a different way to do that with the new version.

https://github.com/V-Sekai/godot-vrm/blob/8e96259b0bf88bca314c41d6cc1c684140dae8dd/vrm_samples/load_at_runtime_scene.gd#L4

**Comment by fire** [comment]
See https://github.com/V-Sekai/VSK_model_explorer/blob/v-sekai/scene/ModelExplorer.gd

**Comment by fire** [comment]
Also there's an open bug about runtime texture import.

See https://github.com/AllenDang/model_explorer_godot4/issues/1 and https://github.com/godotengine/godot/issues/69090

**Comment by EibrielInv** [comment]
Thanks for the info!

**Comment by fire** [comment]
I'm going to close this issue, let me know if there's anything else.
