### ISSUE TITLE
Unwanted reflections in Godot 4 (KHR_materials_unlit not working?)

### ISSUE THREAD

**Issue by grilikin** [V-Sekai/godot-vrm#57]
I might have put the wrong title, but the materials are sometimes glossy when they shouldn't.

I saw that while trying to transition from godot 3 to godot 4.

The problem was very much visible with the following vrm:
https://github.com/madjin/vrm-samples/blob/master/vroid/beta/Victoria_Rubin.vrm

Here's a screenshot from the (expected) godot 3 rendering:
![image](https://user-images.githubusercontent.com/4306557/227024648-72615ac8-8277-45aa-a7b1-90a4fadc310e.png)

And here's the same vrm with godot 4:
![image](https://user-images.githubusercontent.com/4306557/227024725-f4d1b029-7733-45fc-aa27-1dc06afb3599.png)

You can see that there's a huge reflexion on the face and hairs, when there shouldn't be.

I tried playing with the lighting, but even with almost nothing, I see everything black, and the bright white reflexion.

I'm not sure where the problem comes from, but I tried reimporting multiple times, and it just doesn't work.
Note that I did use the godot3 branch of godot-vrm for godot 3, and the main branch for godot4.

Also, it looks like it's specific to only some VRMs (the ones from VRoid Studio perhaps?)

Because one from Zoo Studio looks ok.
Godot 3:
![image](https://user-images.githubusercontent.com/4306557/227026116-f76b5916-a68f-457f-8b06-fef415e17bb0.png)
Godot 4:
![image](https://user-images.githubusercontent.com/4306557/227026151-83dc4755-0da8-49e8-945d-6f4b4a5c8862.png)

**Comment by grilikin** [comment]
See https://github.com/V-Sekai/godot-vrm/issues/58
The line mentioned is causing this issue.

**Comment by lyuma** [comment]
I have disabled Basis universal for now due to some bugs with it. Unfortunately that means we are embedding uncompressed textures.

We will need to work on the workflow for texture compression of VRM assets in the future.
