### ISSUE TITLE
Part of the model skin appears under the skeleton and deforms strangely 

### ISSUE THREAD

**Issue by MMXJacob** [V-Sekai/godot-vrm#59]
A VRM file generated by Zoo Studio has it's body Mesh disconnected from the head and the skeleton when imported:
![image](https://user-images.githubusercontent.com/74930019/227341058-5215bb24-a1ac-4685-a45c-5ee4e278a6b5.png)

The same file in blender is imported properly: 
![image](https://user-images.githubusercontent.com/74930019/227341563-98eef6c3-30c3-4f73-baaa-4173724b70f2.png)

Simple moving the Mesh up in Godot does not fix the issue as the deformation is still incorrect:
![image](https://user-images.githubusercontent.com/74930019/227342080-ef8e9350-87db-4893-b10a-358fbc91405e.png)

Using Godot version Godot_v4.0.1-stable and the master branch of godot-vrm.
This file used to be imported properly in Godot 3.5 with the latest godot-vrm for 3.5.

This is the VRM file I'm importing: [file](https://www.dropbox.com/s/u3ezoer0hd1o4ns/export2023-03-23_1_49_30_PM.vrm?dl=0)

Another VRM file created with Zoo Studio works correctly: 
![image](https://user-images.githubusercontent.com/74930019/227351585-8e56d20a-9ddf-4f7d-926e-4c3c146b7077.png)

**Comment by MMXJacob** [comment]
Loading it in Blender and exporting it from Blender solved the issue.

**Comment by lyuma** [comment]
In Godot 4, this model appears to animate correctly. There were several bugs in the skin retargeting code, so it was likely fixed in the debugging process.
![image](https://github.com/V-Sekai/godot-vrm/assets/39946030/2be06e4f-077f-42dc-9da0-1b76de8837e9)
