### ISSUE TITLE
Visual artifacts with material overlay in compatibility mode

### ISSUE THREAD

**Issue by uguu-org** [V-Sekai/godot-vrm#63]
Surfaces with MToon shader appears to exhibit visual artifacts with overlay material when rendered in compatibility mode:

![compatibility_renderer](https://github.com/V-Sekai/godot-vrm/assets/2000051/150ef5d5-adb7-42d4-bea9-ca6535daa96c)

Maybe some kind of z-fighting due to precision issues?  All these artifacts go away if I do a global replacement of `VIEW_MATRIX * MODEL_MATRIX` with `MODELVIEW_MATRIX` under addons/Godot-MToon-Shader/*.gdshader (21 instances across 7 files):

![compatibility_renderer_with_fix](https://github.com/V-Sekai/godot-vrm/assets/2000051/9bab2538-354a-4a78-9a14-642a1166eae1)

This problem doesn't happen with Forward+ renderer.

![forward_renderer](https://github.com/V-Sekai/godot-vrm/assets/2000051/1102051f-ccf3-44b8-a1e9-b42a7b348e50)

Unfortunately, I can't seem to reproduce this bug on any other model, but the steps I took were:

0. Set compatibility mode.
1. Import VRM with BasisU disabled (see https://github.com/V-Sekai/godot-vrm/issues/58).
2. Select body node, then add new material under "Geometry -> Material Overlay".
3. Set transparency to "Alpha" and Cull mode to "Disabled".

I understand this is not the best bug report without a proper test case, but [Godot's documentation](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/spatial_shader.html) also says "use if possible" next to `MODELVIEW_MATRIX`, so doing this replacement seems like a good idea.

**Comment by lyuma** [comment]
I have applied your suggestion in master. Thanks!

I wonder if Godot 3.x has the same issue. I will consider a backport if I update VRM/MToon for Godot 3
