### ISSUE TITLE
It doesn't work on Godot 4.1

### ISSUE THREAD

**Issue by MalumaDev** [V-Sekai/godot-vrm#69]
When I try to activate it on Godot 4.1 it tells me that there are errors in the script

**Comment by lyuma** [comment]
Would it be possible to try the `vrm1-wip` branch? This code is just being finalized and close to merging into the main branchLet me know if you get errors what they are.On Jul 23, 2023, at 13:26, MalumaDev ***@***.***> wrote:﻿
When I try to activate it on Godot 4.1 it tells me that there are errors in the script

**Comment by MalumaDev** [comment]
It works thx
