### ISSUE TITLE
Implement FastSpringBone to improve springbone performance

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/godot-vrm#70]
See FastSpringBone here: https://github.com/vrm-c/UniVRM/tree/master/Assets/VRM10/Runtime/FastSpringBone
Uses an ECS style solver with Unity's burst compiler.

We need to do a performance benchmark, Then, we can use that benchmark to possibly implement in ECS style in GDScript and/or find specific parts of the springbone solver to port to C++

Supersedes #45

**Comment by fire** [comment]
As far as I can tell the community determined this was not necessary

**Comment by fire** [comment]
Superseded by https://github.com/V-Sekai/godot-vrm/issues/75
