### ISSUE TITLE
Godot V-Sekai can't handle vrm shaders that are using includes

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#81]
@lyuma Can you remove the includes?

**Comment by lyuma** [comment]
We would need to refactor shaders to be dynamically generated or something. I think this is too complex for now.

If this is needed, a script to search for the #include line and paste the contents of the .gdshaderinc should address this issue.

If we put this effort into meta materials or custom scene shaders or other engine related projects, that would open up better opportunities for toon shaders.
