### ISSUE TITLE
Error in Godot 4.1

### ISSUE THREAD

**Issue by subsoap** [V-Sekai/godot-vrm#86]
res://addons/vrm/1.0/VRMC_node_constraint.gd:32 - Parse Error: Could not find type "BoneNodeConstraintApplier" in the current scope.
  res://addons/vrm/plugin.gd:7 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
  res://vsk_model_explorer/core/ModelExplorer.gd:17 - Parse Error: Identifier "FBXDocument" not declared in the current scope.
  res://vsk_model_explorer/core/ModelExplorer.gd:50 - Parse Error: Could not find type "FBXState" in the current scope.
  res://vsk_model_explorer/core/ModelExplorer.gd:50 - Parse Error: Identifier "FBXState" not declared in the current scope.
  res://vsk_model_explorer/core/ModelExplorer.gd:51 - Parse Error: Identifier "FBXState" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2705 - Failed to load script "res://vsk_model_explorer/core/UIController.gd" with error "Parse error". (Use

**Comment by fire** [comment]
Are you're using my model_explorer branch, it's currently setup so I'm using a recent modded version of Godot Engine.


> :warning: **Warning**: This tool uses a custom fork of Godot for 4.3 FBX import. Please check the releases section for more details. [Releases Section](https://github.com/V-Sekai/TOOL_model_explorer/releases)

**Comment by fire** [comment]
In https://github.com/V-Sekai/TOOL_model_explorer/commit/ae6d71cb7cdbf5a3cf12b7e102b19a7e982d1586 I made the fbx importer not error when FBXDocument is missing. Let me know if you have any trouble.
