### ISSUE TITLE
Somewhere the colliders are wrongly imported.

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#93]
1. godot master https://github.com/V-Sekai/godot/releases/tag/groups-4.3.2024-01-20T181514Z
2. nvidia rtx 3090 
3. Windows

![editor_screenshot_2024-01-20T124757](https://github.com/V-Sekai/godot-vrm/assets/32321/fbe79c28-27fd-442f-8550-ccd9cc34da52)

[Black Cat Fire 20240120.zip](https://github.com/V-Sekai/godot-vrm/files/13999195/Black.Cat.Fire.20240120.zip)

**Comment by fire** [comment]
Appears to be rotated

**Comment by lyuma** [comment]
Confirmed still present on the latest version. Must be due to import retargeting

**Comment by fire** [comment]
We discussed how the original model has incorrect colliders but a bug was fixed.
