### ISSUE TITLE
Apply asset library suggestions to ignore folders.

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#98]
Consider adding a .gitattributes file to your repo. This file allows giving extra instructions to Git, such as specifying line endings and listing files not required for your asset to function with the export-ignore directive. This directive removes such files from the resulting ZIP file, preventing them from being downloaded by the asset library users. These are common examples of .gitattributes:

```
# Normalize line endings for all files that Git considers text files.
* text=auto eol=lf

# Only include the addons folder when downloading from the Asset Library.
/**        export-ignore
/addons    !export-ignore
/addons/** !export-ignore
```

https://docs.godotengine.org/en/latest/community/asset_library/submitting_to_assetlib.html

**Comment by lyuma** [comment]
I am not sure this is the best approach.

We need to include vrm_samples since it is recommended for asset library to include examples and this way it can be used as a sample project .

Is there any Godot documentation that explains how export-ignore is intended to be used with the Godot Asset Library?

**Comment by lyuma** [comment]
Oh I see it recommended there when `Addons / Asset Packs` is clicked.

I just don't like needing to exclude samples as a workaround for a UX issue in godot's asset library.

If you add vrm_samples/** and vrm_samples to the .gitattributes then I might be ok with doing this

**Comment by fire** [comment]
I am not convinced this is correct, but wanted to make a note here since it was discussed.

**Comment by Ughuuu** [comment]
If you are exporting an addon, it doesn't make sense to have the user download other files, except the addons directory. Thats what they expect.

The samples one i feel like it would go or should go in a different addon, eg. Godot-vrm-samples. This should be self contained and should contain maybe godot-vrm as well(or should be inside godot-vrm in a samples folder if you feel like)

Why? If you download an addon, you want it in the addons folder, not polluting your files in your project. Imagine similar to node_modules. I would hate if i download something and i dont know where it goes to. Sure, you can normally select and deselect what you want from an addon, but 99% of people click next and install all.

**Comment by Ughuuu** [comment]
> I am not sure this is the best approach.
> 
> 
> 
> We need to include vrm_samples since it is recommended for asset library to include examples and this way it can be used as a sample project .
> 
> 
> 
> from the documentation:
> 
> > If your asset is a library for working with other files, consider including example files in the asset.
> 
> 
> 
> Is there any Godot documentation that explains how export-ignore is intended to be used with the Godot Asset Library?

Is this true though? Do addons have samples? Then it should be inside the addon, not as a separate folder.
If not it should be a separate addon, a samples addon.

**Comment by lyuma** [comment]
We have the only-addon branch for users who use git and do not wish to download a sample project.

Furthermore, the asset library has an option to uncheck unwanted files during import (for the daring few who find that little arrow on the top left).

I simply don't have the bandwidth to maintain and advertise extra asset library projects just to have 8MB of sample assets.
Godot is possibly going to build an asset store at some point, and I can revisit that then.
